In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold, train_test_split, StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import log_loss, roc_auc_score, auc, roc_curve

data_path = 'data/midterm/'
df_train = pd.read_csv(data_path + 'train_offline.csv')
df_test = pd.read_csv(data_path + 'test_offline.csv')

In [2]:
#檢視train資料內容
df_train

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,Date
0,1439408,2632,NaN,NaN,0.0,NaN,20160217.0
1,1439408,2632,8591.0,20:1,0.0,20160217.0,NaN
2,1439408,2632,1078.0,20:1,0.0,20160319.0,NaN
3,1832624,3381,7610.0,200:20,0.0,20160429.0,NaN
4,2029232,3381,11951.0,200:20,1.0,20160129.0,NaN
5,2223968,3381,9776.0,10:5,2.0,20160129.0,NaN
6,73611,2099,12034.0,100:10,NaN,20160207.0,NaN
7,163606,1569,5054.0,200:30,10.0,20160421.0,NaN
8,3273056,4833,7802.0,200:20,10.0,20160130.0,NaN
9,94107,3381,7610.0,200:20,2.0,20160412.0,NaN
10,253750,8390,NaN,NaN,0.0,NaN,20160327.0
11,253750,8390,7531.0,20:5,0.0,20160327.0,NaN
12,376492,1041,13490.0,30:5,2.0,20160127.0,NaN
13,1964720,7884,NaN,NaN,10.0,NaN,20160115.0
14,1964720,7884,6704.0,20:1,10.0,20160215.0,NaN
15,1113008,1041,NaN,NaN,2.0,NaN,20160114.0
16,1113008,1041,11197.0,30:5,2.0,20160114.0,NaN
17,2881376,5341,111.0,30:5,1.0,20160207.0,NaN
18,2881376,8390,7531.0,20:5,0.0,20160321.0,20160329.0
19,2881376,5341,111.0,30:5,1.0,20160207.0,NaN
20,2881376,8390,NaN,NaN,0.0,NaN,20160321.0
21,4061024,2709,2840.0,100:10,10.0,20160129.0,NaN
22,4061024,3381,7610.0,200:20,10.0,20160426.0,NaN
23,4061024,7555,9871.0,30:5,10.0,20160409.0,NaN
24,4061024,3381,9776.0,10:5,10.0,20160129.0,NaN
25,7073472,2934,NaN,NaN,0.0,NaN,20160322.0
26,7073472,3381,7610.0,200:20,0.0,20160326.0,NaN
27,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN
28,7073472,6485,9407.0,100:10,0.0,20160130.0,NaN
29,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN
...,...,...,...,...,...,...,...
1160712,3400544,3485,NaN,NaN,0.0,NaN,20160414.0
1160713,3400544,6454,14031.0,100:10,2.0,20160131.0,NaN
1160714,3400544,3485,NaN,NaN,0.0,NaN,20160115.0
1160715,457900,7907,13118.0,150:30,NaN,20160418.0,NaN
1160716,2876768,6901,NaN,NaN,0.0,NaN,20160421.0
1160717,179830,3381,1807.0,300:30,0.0,20160124.0,NaN
1160718,179830,4059,7166.0,100:10,7.0,20160124.0,NaN
1160719,179830,6434,10050.0,50:5,1.0,20160123.0,NaN
1160720,179830,6284,4567.0,50:10,1.0,20160124.0,NaN
1160721,179830,6284,7379.0,50:10,1.0,20160124.0,NaN
1160722,179830,3710,13056.0,150:10,4.0,20160124.0,NaN
1160723,179830,2099,12034.0,100:10,1.0,20160124.0,NaN
1160724,179830,4660,1480.0,100:10,0.0,20160125.0,NaN
1160725,179830,5341,7751.0,50:10,0.0,20160123.0,NaN
1160726,179830,7555,17.0,30:5,7.0,20160123.0,NaN
1160727,179830,760,3237.0,20:5,0.0,20160124.0,NaN
1160728,179830,2099,12034.0,100:10,1.0,20160203.0,NaN
1160729,343276,4206,NaN,NaN,5.0,NaN,20160425.0
1160730,653784,195,NaN,NaN,0.0,NaN,20160418.0
1160731,653784,195,NaN,NaN,0.0,NaN,20160416.0
1160732,3795296,5341,111.0,30:5,0.0,20160129.0,NaN
1160733,188086,6568,NaN,NaN,0.0,NaN,20160415.0
1160734,188086,6568,4723.0,30:1,0.0,20160415.0,NaN
1160735,188086,6568,NaN,NaN,0.0,NaN,20160417.0
1160736,212662,3532,NaN,NaN,1.0,NaN,20160308.0
1160737,212662,2934,5686.0,30:5,2.0,20160321.0,20160330.0
1160738,212662,3532,5267.0,30:5,1.0,20160322.0,NaN
1160739,212662,2934,5686.0,30:5,2.0,20160321.0,20160322.0
1160740,212662,3532,NaN,NaN,1.0,NaN,20160322.0
1160741,212662,2934,NaN,NaN,2.0,NaN,20160321.0

In [3]:
#檢視test資料內容
df_test

        User_id  Merchant_id  Coupon_id Discount_rate  Distance  Date_received
0       1439408         4663    11002.0        150:20       1.0     20160528.0
1       1439408         2632     8591.0          20:1       0.0     20160613.0
2       1439408         2632        NaN           NaN       0.0            NaN
3       1439408         2632     8591.0          20:1       0.0     20160516.0
4       2029232          450     1532.0          30:5       0.0     20160530.0
5       2029232         6459    12737.0          20:1       0.0     20160519.0
6       2029232         6459        NaN           NaN       0.0            NaN
7       2029232         6459        NaN           NaN       0.0            NaN
8       2747744         6901     1097.0         50:10       NaN     20160606.0
9        196342         1579        NaN           NaN       1.0            NaN
10       196342         1579    10698.0          20:1       1.0     20160606.0
11       253750         6901     2366.0          30:5       0.0     20160518.0
12       343660         4663    11002.0        150:20       NaN     20160528.0
13      4191584         3051        NaN           NaN       0.0            NaN
14      4191584         3051        NaN           NaN       0.0            NaN
15      1113008         3621     2705.0          20:5       0.0     20160524.0
16      1113008         2277     1495.0         30:10       0.0     20160523.0
17      1113008         1361    11166.0          20:1       0.0     20160515.0
18      1113008         1361        NaN           NaN       0.0            NaN
19      1113008         1361    11166.0          20:1       0.0     20160521.0
20      4061024         6485        NaN           NaN      10.0            NaN
21       622296         4874        NaN           NaN       1.0            NaN
22       622296         4874        NaN           NaN       1.0            NaN
23       622296         4874      846.0          50:5       1.0     20160523.0
24      7340736         1539        NaN           NaN       0.0            NaN
25      4064096         4666     6604.0        100:10       0.0     20160602.0
26       114747         2454        NaN           NaN       0.0            NaN
27       114747         6901     2366.0          30:5       0.0     20160523.0
28       114747         6901     1097.0         50:10       0.0     20160605.0
29       114747          760     2418.0          30:5       0.0     20160607.0
...         ...          ...        ...           ...       ...            ...
594112   195862         4666        NaN           NaN       1.0            NaN
594113   195862         4666        NaN           NaN       1.0            NaN
594114   522796         6987        NaN           NaN       0.0            NaN
594115   522796         6987     8689.0        100:10       0.0     20160516.0
594116  4182368          760        NaN           NaN       0.0            NaN
594117  4182368          760        NaN           NaN       0.0            NaN
594118  4182368          760     6103.0          20:5       0.0     20160521.0
594119   261526         7555     2111.0           0.8       1.0     20160511.0
594120  3399008         5341        NaN           NaN       0.0            NaN
594121  3399008         6901     2366.0          30:5       0.0     20160530.0
594122    81675         2709        NaN           NaN      10.0            NaN
594123   118539          760     2418.0          30:5       0.0     20160606.0
594124  3400544         3485        NaN           NaN       0.0            NaN
594125  3400544         3485        NaN           NaN       0.0            NaN
594126  3400544         3485        NaN           NaN       0.0            NaN
594127  3400544         3485        NaN           NaN       0.0            NaN
594128    98091         1553    10027.0          0.95      10.0     20160510.0
594129  2876768         6901     2107.0          30:5       0.0     20160531.0
594130  2876768         6901        NaN           NaN       0.0            NaN
594131  4056416         7177     3469.0          20:1       NaN     20160514.0
594132  4056416         2420    10883.0        100:30       NaN     20160613.0
594133   179830         5341        NaN           NaN       0.0            NaN
594134   188086         6568        NaN           NaN       0.0            NaN
594135   188086         6568        NaN           NaN       0.0            NaN
594136   212662         2934        NaN           NaN       2.0            NaN
594137   212662         2934        NaN           NaN       2.0            NaN
594138   212662         3021     3739.0          30:1       6.0     20160504.0
594139   212662         3021     3739.0          30:1       6.0     20160508.0
594140   752472         7113     1633.0         50:10       6.0     20160613.0
594141   752472         3621     2705.0          20:5       0.0     20160523.0

[594142 rows x 6 columns]

In [4]:
#去掉沒有獲得優惠券的消費者
df_train = df_train.dropna(subset=['Date_received','Coupon_id'])
df_test = df_test.dropna(subset=['Date_received','Coupon_id'])

In [5]:
#change the format of the date
def label(row):
    if np.isnan(row['Date_received']):
        return -1
    if not np.isnan(row['Date']):
        td = pd.to_datetime(row['Date'], format='%Y%m%d') -  pd.to_datetime(row['Date_received'], format='%Y%m%d')
        if td <= pd.Timedelta(15, 'D'):
            return 1
    return 0

#generate the feature : weekday acquired coupon
def getWeekday(row):
    if (np.isnan(row)) or (row==-1):
        return row
    else:
        return pd.to_datetime(row, format = "%Y%m%d").dayofweek+1

# Generate features - coupon discount and distance
def getDiscountType(row):
    if row == 'null':
        return 'null'
    elif ':' in row:
        return 1
    else:
        return 0

#get discount rate
def convertRate(row):
    """Convert discount to rate"""
    if row == 'null':
        return 1.0
    elif ':' in row:
        rows = row.split(':')
        return 1.0 - float(rows[1])/float(rows[0])
    else:
        return float(row)
    
#get original price
def getOringinalPrice(row):
    if ':' in row:
        rows = row.split(':')
        return int(rows[0])
    else:
        return 0

#get the discount
def getDiscount(row):
    if ':' in row:
        rows = row.split(':')
        return int(rows[1])
    else:
        return 0

def processData(df):
    
    # convert discunt_rate
    df['discountRate'] = df['Discount_rate'].astype('str').apply(convertRate)
    df['OriginalPrice'] = df['Discount_rate'].astype('str').apply(getOringinalPrice)
    df['discount'] = df['Discount_rate'].astype('str').apply(getDiscount)
    df['discount_type'] = df['Discount_rate'].astype('str').apply(getDiscountType)
    
    # convert distance
    df.loc[df.Distance.isna(), "Distance"] = 99
    return df

In [6]:
#標示出有無使用優惠券
df_train['label']=df_train.apply(label,axis=1)

In [7]:
print(df_train['label'].value_counts())

0    710665
1     36304
Name: label, dtype: int64

In [8]:
#generate the 'weekday' feature
df_train['weekday'] = df_train['Date_received'].apply(getWeekday)
df_test['weekday'] = df_test['Date_received'].apply(getWeekday)

In [9]:
# weekday_type (weekend = 1)
df_train['weekend'] = df_train['weekday'].astype('str').apply(lambda x : 1 if x in [6,7] else 0 ) # apply to trainset
df_test['weekend'] = df_test['weekday'].astype('str').apply(lambda x : 1 if x in [6,7] else 0 ) # apply to testset
weekdaycols = ['weekday_' + str(i) for i in range(1,8)]

tmpdf = pd.get_dummies(df_train['weekday'].replace(-1, np.nan))
tmpdf.columns = weekdaycols
df_train[weekdaycols] = tmpdf

tmpdf = pd.get_dummies(df_test['weekday'].replace(-1, np.nan))
tmpdf.columns = weekdaycols
df_test[weekdaycols] = tmpdf

In [10]:
#generate four new feature
processData(df_train)
processData(df_test)

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,weekday,weekend,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,weekday_6,weekday_7,discountRate,OriginalPrice,discount,discount_type
0,1439408,4663,11002.0,150:20,1.0,20160528.0,6,0,0,0,0,0,0,1,0,0.866667,150,20,1
1,1439408,2632,8591.0,20:1,0.0,20160613.0,1,0,1,0,0,0,0,0,0,0.950000,20,1,1
3,1439408,2632,8591.0,20:1,0.0,20160516.0,1,0,1,0,0,0,0,0,0,0.950000,20,1,1
4,2029232,450,1532.0,30:5,0.0,20160530.0,1,0,1,0,0,0,0,0,0,0.833333,30,5,1
5,2029232,6459,12737.0,20:1,0.0,20160519.0,4,0,0,0,0,1,0,0,0,0.950000,20,1,1
8,2747744,6901,1097.0,50:10,99.0,20160606.0,1,0,1,0,0,0,0,0,0,0.800000,50,10,1
10,196342,1579,10698.0,20:1,1.0,20160606.0,1,0,1,0,0,0,0,0,0,0.950000,20,1,1
11,253750,6901,2366.0,30:5,0.0,20160518.0,3,0,0,0,1,0,0,0,0,0.833333,30,5,1
12,343660,4663,11002.0,150:20,99.0,20160528.0,6,0,0,0,0,0,0,1,0,0.866667,150,20,1
15,1113008,3621,2705.0,20:5,0.0,20160524.0,2,0,0,1,0,0,0,0,0,0.750000,20,5,1
16,1113008,2277,1495.0,30:10,0.0,20160523.0,1,0,1,0,0,0,0,0,0,0.666667,30,10,1
17,1113008,1361,11166.0,20:1,0.0,20160515.0,7,0,0,0,0,0,0,0,1,0.950000,20,1,1
19,1113008,1361,11166.0,20:1,0.0,20160521.0,6,0,0,0,0,0,0,1,0,0.950000,20,1,1
23,622296,4874,846.0,50:5,1.0,20160523.0,1,0,1,0,0,0,0,0,0,0.900000,50,5,1
25,4064096,4666,6604.0,100:10,0.0,20160602.0,4,0,0,0,0,1,0,0,0,0.900000,100,10,1
27,114747,6901,2366.0,30:5,0.0,20160523.0,1,0,1,0,0,0,0,0,0,0.833333,30,5,1
28,114747,6901,1097.0,50:10,0.0,20160605.0,7,0,0,0,0,0,0,0,1,0.800000,50,10,1
29,114747,760,2418.0,30:5,0.0,20160607.0,2,0,0,1,0,0,0,0,0,0.833333,30,5,1
30,114747,6901,2107.0,30:5,0.0,20160605.0,7,0,0,0,0,0,0,0,1,0.833333,30,5,1
42,245878,760,2418.0,30:5,0.0,20160601.0,3,0,0,0,1,0,0,0,0,0.833333,30,5,1
43,3409760,6901,2366.0,30:5,7.0,20160530.0,1,0,1,0,0,0,0,0,0,0.833333,30,5,1
44,2231648,3621,2705.0,20:5,1.0,20160522.0,7,0,0,0,0,0,0,0,1,0.750000,20,5,1
45,1314224,760,2418.0,30:5,2.0,20160611.0,6,0,0,0,0,0,0,1,0,0.833333,30,5,1
46,3283808,6189,13606.0,30:5,2.0,20160524.0,2,0,0,1,0,0,0,0,0,0.833333,30,5,1
48,127227,3621,2705.0,20:5,0.0,20160510.0,2,0,0,1,0,0,0,0,0,0.750000,20,5,1
49,197110,8479,7360.0,10:1,0.0,20160526.0,4,0,0,0,0,1,0,0,0,0.900000,10,1,1
53,559320,3621,2705.0,20:5,2.0,20160520.0,5,0,0,0,0,0,1,0,0,0.750000,20,5,1
54,3548000,450,1532.0,30:5,99.0,20160527.0,5,0,0,0,0,0,1,0,0,0.833333,30,5,1
55,4474560,6504,2348.0,30:1,1.0,20160505.0,4,0,0,0,0,1,0,0,0,0.966667,30,1,1
56,5525184,760,2418.0,30:5,0.0,20160602.0,4,0,0,0,0,1,0,0,0,0.833333,30,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594084,4680384,5717,8192.0,20:5,0.0,20160522.0,7,0,0,0,0,0,0,0,1,0.750000,20,5,1
594085,4680384,8386,4283.0,100:20,0.0,20160531.0,2,0,0,1,0,0,0,0,0,0.800000,100,20,1
594088,6253248,760,2418.0,30:5,10.0,20160601.0,3,0,0,0,1,0,0,0,0,0.833333,30,5,1
594094,228214,6762,6023.0,100:30,0.0,20160513.0,5,0,0,0,0,0,1,0,0,0.700000,100,30,1
594095,552408,4663,13304.0,150:20,0.0,20160526.0,4,0,0,0,0,1,0,0,0,0.866667,150,20,1
594096,552408,4663,11002.0,150:20,0.0,20160528.0,6,0,0,0,0,0,0,1,0,0.866667,150,20,1
594099,187414,7580,8640.0,200:20,99.0,20160502.0,1,0,1,0,0,0,0,0,0,0.900000,200,20,1
594101,195670,3621,2705.0,20:5,10.0,20160527.0,5,0,0,0,0,0,1,0,0,0.750000,20,5,1
594102,1106864,760,2418.0,30:5,0.0,20160613.0,1,0,1,0,0,0,0,0,0,0.833333,30,5,1
594103,154774,7903,8137.0,20:1,99.0,20160526.0,4,0,0,0,0,1,0,0,0,0.950000,20,1,1
594104,489772,3621,2705.0,20:5,0.0,20160524.0,2,0,0,1,0,0,0,0,0,0.750000,20,5,1
594105,717528,629,2427.0,30:10,0.0,20160524.0,2,0,0,1,0,0,0,0,0,0.666667,30,10,1
594107,881496,6485,2079.0,30:5,3.0,20160522.0,7,0,0,0,0,0,0,0,1,0.833333,30,5,1
594108,1894064,760,2418.0,30:5,0.0,20160609.0,4,0,0,0,0,1,0,0,0,0.833333,30,5,1
594109,2090672,3449,13425.0,50:10,99.0,20160509.0,1,0,1,0,0,0,0,0,0,0.800000,50,10,1
594110,118395,2703,3321.0,0.95,0.0,20160607.0,2,0,0,1,0,0,0,0,0,0.950000,0,0,0
594111,195862,4666,6604.0,100:10,1.0,20160602.0,4,0,0,0,0,1,0,0,0,0.900000,100,10,1
594115,522796,6987,8689.0,100:10,0.0,20160516.0,1,0,1,0,0,0,0,0,0,0.900000,100,10,1
594118,4182368,760,6103.0,20:5,0.0,20160521.0,6,0,0,0,0,0,0,1,0,0.750000,20,5,1
594119,261526,7555,2111.0,0.8,1.0,20160511.0,3,0,0,0,1,0,0,0,0,0.800000,0,0,0
594121,3399008,6901,2366.0,30:5,0.0,20160530.0,1,0,1,0,0,0,0,0,0,0.833333,30,5,1
594123,118539,760,2418.0,30:5,0.0,20160606.0,1,0,1,0,0,0,0,0,0,0.833333,30,5,1
594128,98091,1553,10027.0,0.95,10.0,20160510.0,2,0,0,1,0,0,0,0,0,0.950000,0,0,0
594129,2876768,6901,2107.0,30:5,0.0,20160531.0,2,0,0,1,0,0,0,0,0,0.833333,30,5,1
594131,4056416,7177,3469.0,20:1,99.0,20160514.0,6,0,0,0,0,0,0,1,0,0.950000,20,1,1
594132,4056416,2420,10883.0,100:30,99.0,20160613.0,1,0,1,0,0,0,0,0,0,0.700000,100,30,1
594138,212662,3021,3739.0,30:1,6.0,20160504.0,3,0,0,0,1,0,0,0,0,0.966667,30,1,1
594139,212662,3021,3739.0,30:1,6.0,20160508.0,7,0,0,0,0,0,0,0,1,0.966667,30,1,1
594140,752472,7113,1633.0,50:10,6.0,20160613.0,1,0,1,0,0,0,0,0,0,0.800000,50,10,1
594141,752472,3621,2705.0,20:5,0.0,20160523.0,1,0,1,0,0,0,0,0,0,0.750000,20,5,1

In [11]:
def split_train_valid(row, date_cut="20160416"):
    is_train = True if pd.to_datetime(row, format="%Y%m%d") < pd.to_datetime(date_cut, format="%Y%m%d") else False
    return is_train
    
df = df_train[df_train['label'] != -1].copy()
df["is_train"] = df["Date_received"].apply(split_train_valid)
train = df[df["is_train"]]
valid = df[~df["is_train"]]
train.reset_index(drop=True, inplace=True)
valid.reset_index(drop=True, inplace=True)
train

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,Date,label,weekday,weekend,...,weekday_3,weekday_4,weekday_5,weekday_6,weekday_7,discountRate,OriginalPrice,discount,discount_type,is_train
0,1439408,2632,8591.0,20:1,0.0,20160217.0,NaN,0,3,0,...,1,0,0,0,0,0.950000,20,1,1,True
1,1439408,2632,1078.0,20:1,0.0,20160319.0,NaN,0,6,0,...,0,0,0,1,0,0.950000,20,1,1,True
2,2029232,3381,11951.0,200:20,1.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,200,20,1,True
3,2223968,3381,9776.0,10:5,2.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.500000,10,5,1,True
4,73611,2099,12034.0,100:10,99.0,20160207.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
5,3273056,4833,7802.0,200:20,10.0,20160130.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,200,20,1,True
6,94107,3381,7610.0,200:20,2.0,20160412.0,NaN,0,2,0,...,0,0,0,0,0,0.900000,200,20,1,True
7,253750,8390,7531.0,20:5,0.0,20160327.0,NaN,0,7,0,...,0,0,0,0,1,0.750000,20,5,1,True
8,376492,1041,13490.0,30:5,2.0,20160127.0,NaN,0,3,0,...,1,0,0,0,0,0.833333,30,5,1,True
9,1964720,7884,6704.0,20:1,10.0,20160215.0,NaN,0,1,0,...,0,0,0,0,0,0.950000,20,1,1,True
10,1113008,1041,11197.0,30:5,2.0,20160114.0,NaN,0,4,0,...,0,1,0,0,0,0.833333,30,5,1,True
11,2881376,5341,111.0,30:5,1.0,20160207.0,NaN,0,7,0,...,0,0,0,0,1,0.833333,30,5,1,True
12,2881376,8390,7531.0,20:5,0.0,20160321.0,20160329.0,1,1,0,...,0,0,0,0,0,0.750000,20,5,1,True
13,2881376,5341,111.0,30:5,1.0,20160207.0,NaN,0,7,0,...,0,0,0,0,1,0.833333,30,5,1,True
14,4061024,2709,2840.0,100:10,10.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,100,10,1,True
15,4061024,7555,9871.0,30:5,10.0,20160409.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,True
16,4061024,3381,9776.0,10:5,10.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.500000,10,5,1,True
17,7073472,3381,7610.0,200:20,0.0,20160326.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,200,20,1,True
18,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN,0,2,0,...,0,0,0,0,0,0.833333,30,5,1,True
19,7073472,6485,9407.0,100:10,0.0,20160130.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,100,10,1,True
20,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN,0,2,0,...,0,0,0,0,0,0.833333,30,5,1,True
21,106443,7019,3887.0,100:10,0.0,20160131.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
22,442156,6284,7379.0,50:10,10.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.800000,50,10,1,True
23,4717248,3381,11951.0,200:20,4.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,200,20,1,True
24,2621792,4433,190.0,200:20,99.0,20160131.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,200,20,1,True
25,262252,7706,416.0,100:10,0.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,100,10,1,True
26,262252,2099,12034.0,100:10,0.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,100,10,1,True
27,114747,760,3237.0,20:5,0.0,20160128.0,NaN,0,4,0,...,0,1,0,0,0,0.750000,20,5,1,True
28,114747,5341,111.0,30:5,0.0,20160127.0,20160221.0,0,3,0,...,1,0,0,0,0,0.833333,30,5,1,True
29,114747,5341,111.0,30:5,0.0,20160207.0,20160218.0,1,7,0,...,0,0,0,0,1,0.833333,30,5,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667723,81627,1569,5054.0,200:30,8.0,20160415.0,NaN,0,5,0,...,0,0,1,0,0,0.850000,200,30,1,True
667724,6796992,3381,1807.0,300:30,4.0,20160131.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,300,30,1,True
667725,6796992,7019,3887.0,100:10,10.0,20160130.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,100,10,1,True
667726,3399008,5341,11539.0,30:5,0.0,20160207.0,20160211.0,1,7,0,...,0,0,0,0,1,0.833333,30,5,1,True
667727,261622,3381,7610.0,200:20,1.0,20160407.0,NaN,0,4,0,...,0,1,0,0,0,0.900000,200,20,1,True
667728,1306544,2804,10326.0,30:5,1.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.833333,30,5,1,True
667729,1306544,6434,10050.0,50:5,0.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.900000,50,5,1,True
667730,1306544,8037,1789.0,30:5,0.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.833333,30,5,1,True
667731,1306544,4660,1480.0,100:10,1.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.900000,100,10,1,True
667732,1437872,7706,416.0,100:10,4.0,20160129.0,20160202.0,1,5,0,...,0,0,1,0,0,0.900000,100,10,1,True
667733,1437872,7706,12097.0,100:10,4.0,20160202.0,NaN,0,2,0,...,0,0,0,0,0,0.900000,100,10,1,True
667734,1437872,3381,11951.0,200:20,2.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,200,20,1,True
667735,3400544,6454,14031.0,100:10,2.0,20160131.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
667736,179830,3381,1807.0,300:30,0.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,300,30,1,True
667737,179830,4059,7166.0,100:10,7.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
667738,179830,6434,10050.0,50:5,1.0,20160123.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,50,5,1,True
667739,179830,6284,4567.0,50:10,1.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.800000,50,10,1,True
667740,179830,6284,7379.0,50:10,1.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.800000,50,10,1,True
667741,179830,3710,13056.0,150:10,4.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.933333,150,10,1,True
667742,179830,2099,12034.0,100:10,1.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
667743,179830,4660,1480.0,100:10,0.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.900000,100,10,1,True
667744,179830,5341,7751.0,50:10,0.0,20160123.0,NaN,0,6,0,...,0,0,0,1,0,0.800000,50,10,1,True
667745,179830,7555,17.0,30:5,7.0,20160123.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,True
667746,179830,760,3237.0,20:5,0.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.750000,20,5,1,True
667747,179830,2099,12034.0,100:10,1.0,20160203.0,NaN,0,3,0,...,1,0,0,0,0,0.900000,100,10,1,True
667748,3795296,5341,111.0,30:5,0.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.833333,30,5,1,True
667749,188086,6568,4723.0,30:1,0.0,20160415.0,NaN,0,5,0,...,0,0,1,0,0,0.966667,30,1,1,True
667750,212662,2934,5686.0,30:5,2.0,20160321.0,20160330.0,1,1,0,...,0,0,0,0,0,0.833333,30,5,1,True
667751,212662,3532,5267.0,30:5,1.0,20160322.0,NaN,0,2,0,...,0,0,0,0,0,0.833333,30,5,1,True
667752,212662,2934,5686.0,30:5,2.0,20160321.0,20160322.0,1,1,0,...,0,0,0,0,0,0.833333,30,5,1,True

In [12]:
train

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,Date,label,weekday,weekend,...,weekday_3,weekday_4,weekday_5,weekday_6,weekday_7,discountRate,OriginalPrice,discount,discount_type,is_train
0,1439408,2632,8591.0,20:1,0.0,20160217.0,NaN,0,3,0,...,1,0,0,0,0,0.950000,20,1,1,True
1,1439408,2632,1078.0,20:1,0.0,20160319.0,NaN,0,6,0,...,0,0,0,1,0,0.950000,20,1,1,True
2,2029232,3381,11951.0,200:20,1.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,200,20,1,True
3,2223968,3381,9776.0,10:5,2.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.500000,10,5,1,True
4,73611,2099,12034.0,100:10,99.0,20160207.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
5,3273056,4833,7802.0,200:20,10.0,20160130.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,200,20,1,True
6,94107,3381,7610.0,200:20,2.0,20160412.0,NaN,0,2,0,...,0,0,0,0,0,0.900000,200,20,1,True
7,253750,8390,7531.0,20:5,0.0,20160327.0,NaN,0,7,0,...,0,0,0,0,1,0.750000,20,5,1,True
8,376492,1041,13490.0,30:5,2.0,20160127.0,NaN,0,3,0,...,1,0,0,0,0,0.833333,30,5,1,True
9,1964720,7884,6704.0,20:1,10.0,20160215.0,NaN,0,1,0,...,0,0,0,0,0,0.950000,20,1,1,True
10,1113008,1041,11197.0,30:5,2.0,20160114.0,NaN,0,4,0,...,0,1,0,0,0,0.833333,30,5,1,True
11,2881376,5341,111.0,30:5,1.0,20160207.0,NaN,0,7,0,...,0,0,0,0,1,0.833333,30,5,1,True
12,2881376,8390,7531.0,20:5,0.0,20160321.0,20160329.0,1,1,0,...,0,0,0,0,0,0.750000,20,5,1,True
13,2881376,5341,111.0,30:5,1.0,20160207.0,NaN,0,7,0,...,0,0,0,0,1,0.833333,30,5,1,True
14,4061024,2709,2840.0,100:10,10.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,100,10,1,True
15,4061024,7555,9871.0,30:5,10.0,20160409.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,True
16,4061024,3381,9776.0,10:5,10.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.500000,10,5,1,True
17,7073472,3381,7610.0,200:20,0.0,20160326.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,200,20,1,True
18,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN,0,2,0,...,0,0,0,0,0,0.833333,30,5,1,True
19,7073472,6485,9407.0,100:10,0.0,20160130.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,100,10,1,True
20,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN,0,2,0,...,0,0,0,0,0,0.833333,30,5,1,True
21,106443,7019,3887.0,100:10,0.0,20160131.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
22,442156,6284,7379.0,50:10,10.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.800000,50,10,1,True
23,4717248,3381,11951.0,200:20,4.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,200,20,1,True
24,2621792,4433,190.0,200:20,99.0,20160131.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,200,20,1,True
25,262252,7706,416.0,100:10,0.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,100,10,1,True
26,262252,2099,12034.0,100:10,0.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,100,10,1,True
27,114747,760,3237.0,20:5,0.0,20160128.0,NaN,0,4,0,...,0,1,0,0,0,0.750000,20,5,1,True
28,114747,5341,111.0,30:5,0.0,20160127.0,20160221.0,0,3,0,...,1,0,0,0,0,0.833333,30,5,1,True
29,114747,5341,111.0,30:5,0.0,20160207.0,20160218.0,1,7,0,...,0,0,0,0,1,0.833333,30,5,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667723,81627,1569,5054.0,200:30,8.0,20160415.0,NaN,0,5,0,...,0,0,1,0,0,0.850000,200,30,1,True
667724,6796992,3381,1807.0,300:30,4.0,20160131.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,300,30,1,True
667725,6796992,7019,3887.0,100:10,10.0,20160130.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,100,10,1,True
667726,3399008,5341,11539.0,30:5,0.0,20160207.0,20160211.0,1,7,0,...,0,0,0,0,1,0.833333,30,5,1,True
667727,261622,3381,7610.0,200:20,1.0,20160407.0,NaN,0,4,0,...,0,1,0,0,0,0.900000,200,20,1,True
667728,1306544,2804,10326.0,30:5,1.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.833333,30,5,1,True
667729,1306544,6434,10050.0,50:5,0.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.900000,50,5,1,True
667730,1306544,8037,1789.0,30:5,0.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.833333,30,5,1,True
667731,1306544,4660,1480.0,100:10,1.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.900000,100,10,1,True
667732,1437872,7706,416.0,100:10,4.0,20160129.0,20160202.0,1,5,0,...,0,0,1,0,0,0.900000,100,10,1,True
667733,1437872,7706,12097.0,100:10,4.0,20160202.0,NaN,0,2,0,...,0,0,0,0,0,0.900000,100,10,1,True
667734,1437872,3381,11951.0,200:20,2.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,200,20,1,True
667735,3400544,6454,14031.0,100:10,2.0,20160131.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
667736,179830,3381,1807.0,300:30,0.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,300,30,1,True
667737,179830,4059,7166.0,100:10,7.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
667738,179830,6434,10050.0,50:5,1.0,20160123.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,50,5,1,True
667739,179830,6284,4567.0,50:10,1.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.800000,50,10,1,True
667740,179830,6284,7379.0,50:10,1.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.800000,50,10,1,True
667741,179830,3710,13056.0,150:10,4.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.933333,150,10,1,True
667742,179830,2099,12034.0,100:10,1.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,100,10,1,True
667743,179830,4660,1480.0,100:10,0.0,20160125.0,NaN,0,1,0,...,0,0,0,0,0,0.900000,100,10,1,True
667744,179830,5341,7751.0,50:10,0.0,20160123.0,NaN,0,6,0,...,0,0,0,1,0,0.800000,50,10,1,True
667745,179830,7555,17.0,30:5,7.0,20160123.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,True
667746,179830,760,3237.0,20:5,0.0,20160124.0,NaN,0,7,0,...,0,0,0,0,1,0.750000,20,5,1,True
667747,179830,2099,12034.0,100:10,1.0,20160203.0,NaN,0,3,0,...,1,0,0,0,0,0.900000,100,10,1,True
667748,3795296,5341,111.0,30:5,0.0,20160129.0,NaN,0,5,0,...,0,0,1,0,0,0.833333,30,5,1,True
667749,188086,6568,4723.0,30:1,0.0,20160415.0,NaN,0,5,0,...,0,0,1,0,0,0.966667,30,1,1,True
667750,212662,2934,5686.0,30:5,2.0,20160321.0,20160330.0,1,1,0,...,0,0,0,0,0,0.833333,30,5,1,True
667751,212662,3532,5267.0,30:5,1.0,20160322.0,NaN,0,2,0,...,0,0,0,0,0,0.833333,30,5,1,True
667752,212662,2934,5686.0,30:5,2.0,20160321.0,20160322.0,1,1,0,...,0,0,0,0,0,0.833333,30,5,1,True

In [14]:
valid

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,Date,label,weekday,weekend,...,weekday_3,weekday_4,weekday_5,weekday_6,weekday_7,discountRate,OriginalPrice,discount,discount_type,is_train
0,1832624,3381,7610.0,200:20,0.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,200,20,1,False
1,163606,1569,5054.0,200:30,10.0,20160421.0,NaN,0,4,0,...,0,1,0,0,0,0.850000,200,30,1,False
2,4061024,3381,7610.0,200:20,10.0,20160426.0,NaN,0,2,0,...,0,0,0,0,0,0.900000,200,20,1,False
3,106443,450,3732.0,30:5,99.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.833333,30,5,1,False
4,114747,1569,5054.0,200:30,9.0,20160426.0,NaN,0,2,0,...,0,0,0,0,0,0.850000,200,30,1,False
5,6038208,1569,5054.0,200:30,0.0,20160417.0,NaN,0,7,0,...,0,0,0,0,1,0.850000,200,30,1,False
6,623832,4442,7643.0,100:50,99.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.500000,100,50,1,False
7,3548000,3381,7610.0,200:20,10.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,200,20,1,False
8,361900,450,3732.0,30:5,0.0,20160430.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,False
9,527832,450,3732.0,30:5,1.0,20160430.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,False
10,460972,3381,7610.0,200:20,3.0,20160421.0,NaN,0,4,0,...,0,1,0,0,0,0.900000,200,20,1,False
11,90699,7555,9871.0,30:5,3.0,20160420.0,NaN,0,3,0,...,1,0,0,0,0,0.833333,30,5,1,False
12,2116448,2436,3992.0,30:5,10.0,20160422.0,NaN,0,5,0,...,0,0,1,0,0,0.833333,30,5,1,False
13,2904416,3381,7610.0,200:20,0.0,20160425.0,NaN,0,1,0,...,0,0,0,0,0,0.900000,200,20,1,False
14,103083,2436,3992.0,30:5,0.0,20160422.0,NaN,0,5,0,...,0,0,1,0,0,0.833333,30,5,1,False
15,222550,7717,9614.0,20:1,0.0,20160424.0,NaN,0,7,0,...,0,0,0,0,1,0.950000,20,1,1,False
16,1780400,450,3732.0,30:5,10.0,20160424.0,NaN,0,7,0,...,0,0,0,0,1,0.833333,30,5,1,False
17,78555,3381,7610.0,200:20,0.0,20160421.0,NaN,0,4,0,...,0,1,0,0,0,0.900000,200,20,1,False
18,330988,7555,9871.0,30:5,10.0,20160416.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,False
19,629592,7974,8952.0,50:10,99.0,20160425.0,NaN,0,1,0,...,0,0,0,0,0,0.800000,50,10,1,False
20,891864,2963,1978.0,20:1,10.0,20160425.0,NaN,0,1,0,...,0,0,0,0,0,0.950000,20,1,1,False
21,119739,450,3732.0,30:5,0.0,20160423.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,False
22,91131,1569,5054.0,200:30,3.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.850000,200,30,1,False
23,99387,450,3732.0,30:5,1.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.833333,30,5,1,False
24,99387,7555,9871.0,30:5,0.0,20160418.0,NaN,0,1,0,...,0,0,0,0,0,0.833333,30,5,1,False
25,5055168,5430,9068.0,50:5,1.0,20160420.0,NaN,0,3,0,...,1,0,0,0,0,0.900000,50,5,1,False
26,463468,1569,5054.0,200:30,5.0,20160424.0,NaN,0,7,0,...,0,0,0,0,1,0.850000,200,30,1,False
27,463468,3381,7610.0,200:20,9.0,20160428.0,NaN,0,4,0,...,0,1,0,0,0,0.900000,200,20,1,False
28,207190,3381,7610.0,200:20,2.0,20160427.0,NaN,0,3,0,...,1,0,0,0,0,0.900000,200,20,1,False
29,764376,7555,9871.0,30:5,8.0,20160416.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79186,420652,1569,5054.0,200:30,7.0,20160430.0,NaN,0,6,0,...,0,0,0,1,0,0.850000,200,30,1,False
79187,169654,6481,637.0,30:5,99.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.833333,30,5,1,False
79188,777432,1569,5054.0,200:30,10.0,20160426.0,NaN,0,2,0,...,0,0,0,0,0,0.850000,200,30,1,False
79189,170038,6481,637.0,30:5,9.0,20160426.0,NaN,0,2,0,...,0,0,0,0,0,0.833333,30,5,1,False
79190,170038,3646,4457.0,20:5,9.0,20160430.0,NaN,0,6,0,...,0,0,0,1,0,0.750000,20,5,1,False
79191,1492400,7086,602.0,10:1,0.0,20160423.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,10,1,1,False
79192,202966,1569,5054.0,200:30,10.0,20160425.0,NaN,0,1,0,...,0,0,0,0,0,0.850000,200,30,1,False
79193,202966,450,3732.0,30:5,10.0,20160421.0,NaN,0,4,0,...,0,1,0,0,0,0.833333,30,5,1,False
79194,340588,984,8592.0,10:1,0.0,20160428.0,NaN,0,4,0,...,0,1,0,0,0,0.900000,10,1,1,False
79195,340588,4579,7142.0,10:1,0.0,20160429.0,20160430.0,1,5,0,...,0,0,1,0,0,0.900000,10,1,1,False
79196,2200928,7555,9871.0,30:5,10.0,20160420.0,NaN,0,3,0,...,1,0,0,0,0,0.833333,30,5,1,False
79197,260566,7884,6704.0,20:1,6.0,20160418.0,NaN,0,1,0,...,0,0,0,0,0,0.950000,20,1,1,False
79198,878424,1569,5054.0,200:30,3.0,20160418.0,NaN,0,1,0,...,0,0,0,0,0,0.850000,200,30,1,False
79199,122139,7422,4727.0,0.8,1.0,20160425.0,20160425.0,1,1,0,...,0,0,0,0,0,0.800000,0,0,0,False
79200,780504,3381,7610.0,200:20,99.0,20160426.0,NaN,0,2,0,...,0,0,0,0,0,0.900000,200,20,1,False
79201,4935360,8181,11860.0,30:10,0.0,20160425.0,NaN,0,1,0,...,0,0,0,0,0,0.666667,30,10,1,False
79202,6511296,2436,3992.0,30:5,0.0,20160430.0,NaN,0,6,0,...,0,0,0,1,0,0.833333,30,5,1,False
79203,1104560,3381,7610.0,200:20,0.0,20160417.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,200,20,1,False
79204,6253248,6980,5387.0,30:1,0.0,20160424.0,NaN,0,7,0,...,0,0,0,0,1,0.966667,30,1,1,False
79205,374764,3381,7610.0,200:20,6.0,20160426.0,NaN,0,2,0,...,0,0,0,0,0,0.900000,200,20,1,False
79206,1044696,7555,9871.0,30:5,10.0,20160418.0,NaN,0,1,0,...,0,0,0,0,0,0.833333,30,5,1,False
79207,3916640,2436,3992.0,30:5,0.0,20160428.0,NaN,0,4,0,...,0,1,0,0,0,0.833333,30,5,1,False
79208,2090672,3449,426.0,100:20,99.0,20160425.0,NaN,0,1,0,...,0,0,0,0,0,0.800000,100,20,1,False
79209,553944,3381,7610.0,200:20,4.0,20160425.0,NaN,0,1,0,...,0,0,0,0,0,0.900000,200,20,1,False
79210,3526496,3381,7610.0,200:20,3.0,20160417.0,NaN,0,7,0,...,0,0,0,0,1,0.900000,200,20,1,False
79211,522796,1812,2112.0,100:20,0.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.800000,100,20,1,False
79212,522796,1812,2692.0,100:20,0.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.800000,100,20,1,False
79213,4182368,2050,13543.0,200:20,4.0,20160430.0,NaN,0,6,0,...,0,0,0,1,0,0.900000,200,20,1,False
79214,73419,3381,7610.0,200:20,4.0,20160429.0,NaN,0,5,0,...,0,0,1,0,0,0.900000,200,20,1,False
79215,457900,7907,13118.0,150:30,99.0,20160418.0,NaN,0,1,0,...,0,0,0,0,0,0.800000,150,30,1,False

In [15]:
newFeature = ['discountRate','discount_type','OriginalPrice','discount','Distance',
              'weekday', 'weekend'] + weekdaycols
newFeature

['discountRate',
 'discount_type',
 'OriginalPrice',
 'discount',
 'Distance',
 'weekday',
 'weekend',
 'weekday_1',
 'weekday_2',
 'weekday_3',
 'weekday_4',
 'weekday_5',
 'weekday_6',
 'weekday_7']

In [16]:
predictors = newFeature

def check_model(data, predictors):
    
    classifier = lambda: SGDClassifier(
        loss='log', 
        penalty='elasticnet', 
        fit_intercept=True, 
        max_iter=100, 
        shuffle=True, 
        n_jobs=1,
        class_weight=None)

    model = Pipeline(steps=[
        ('ss', StandardScaler()),
        ('en', classifier())
    ])

    parameters = {
        'en__alpha': [ 0.001, 0.01, 0.1],
        'en__l1_ratio': [ 0.001, 0.01, 0.1]
    }

    folder = StratifiedKFold(n_splits=3, shuffle=True)
    
    grid_search = GridSearchCV(
        model, 
        parameters, 
        cv=folder, 
        n_jobs=-1, 
        verbose=1)
    grid_search = grid_search.fit(data[predictors], 
                                  data['label'])
    
    return grid_search
model = check_model(train, predictors)

Fitting 3 folds for each of 9 candidates, totalling 27 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  27 out of  27 | elapsed:  1.8min finished

In [17]:
y_valid_pred = model.predict_proba(valid[predictors])
valid1 = valid.copy()
valid1['pred_prob'] = y_valid_pred[:, 1]

In [19]:
from sklearn.metrics import roc_auc_score, accuracy_score
auc_score = roc_auc_score(y_true=valid.label, y_score=y_valid_pred[:,1])
acc = accuracy_score(y_true=valid.label, y_pred=y_valid_pred.argmax(axis=1))
print("Validation AUC: {:.3f}, Accuracy: {:.3f}".format(auc_score, acc))

Validation AUC: 0.743, Accuracy: 0.952

In [20]:
targetset = df_test.copy()
print(targetset.shape)
targetset = targetset[~targetset.Coupon_id.isna()]
targetset.reset_index(drop=True, inplace=True)
testset = targetset[predictors].copy()

y_test_pred = model.predict_proba(testset[predictors])
test1 = testset.copy()
test1['pred_prob'] = y_test_pred[:, 1]
print(test1.shape)

(306313, 19)
(306313, 15)

In [21]:
output = pd.concat((targetset[["User_id", "Coupon_id", "Date_received"]], test1["pred_prob"]), axis=1)
print(output.shape)

output.loc[:, "User_id"] = output["User_id"].apply(lambda x:str(int(x)))
output.loc[:, "Coupon_id"] = output["Coupon_id"].apply(lambda x:str(int(x)))
output.loc[:, "Date_received"] = output["Date_received"].apply(lambda x:str(int(x)))
output["uid"] = output[["User_id", "Coupon_id", "Date_received"]].apply(lambda x: '_'.join(x.values), axis=1)
output.reset_index(drop=True, inplace=True)

(306313, 4)

In [23]:
#輸出submission檔案
out = output.groupby("uid", as_index=False).mean()
out = out[["uid", "pred_prob"]]
out.columns = ["uid", "label"]
out.to_csv("Day_051_HW.csv", header=["uid", "label"], index=False)
out.head()

304096